EXTRA_CFLAGS := $(extra_cflags)
KBUILD_EXTRA_SYMBOLS = $(src)/../buffer/Module.symvers \
                       $(src)/../driver/Module.symvers

obj-m := swap_writer.o
swap_writer-y := swap_writer_module.o \
                 debugfs_writer.o \
                 event_filter.o

swap_writer-$(CONFIG_ARM) += kernel_operations_arm.o
swap_writer-$(CONFIG_X86) += kernel_operations_x86.o
