EXTRA_CFLAGS := $(extra_cflags)

obj-m := swap_kprobe.o
swap_kprobe-y := swap_kprobes.o \
                 swap_kprobes_deps.o \
                 swap_slots.o \
                 swap_td_raw.o \
                 swap_ktd.o

### ARM
swap_kprobe-$(CONFIG_ARM) += arch/arm/swap-asm/swap_kprobes.o \
                             arch/arm/swap-asm/trampoline_arm.o
ifeq ($(CONFIG_STRICT_MEMORY_RWX), y)
swap_kprobe-$(CONFIG_ARM) += arch/arm/swap-asm/memory_rwx.o
endif #ifeq ($(CONFIG_STRICT_MEMORY_RWX), y)


### X86
swap_kprobe-$(CONFIG_X86) += arch/x86/swap-asm/swap_kprobes.o
