EXTRA_CFLAGS := $(android_opt) $(board_opt)

obj-m := swap_kprobe.o
swap_kprobe-y := dbi_kprobes_deps.o dbi_insn_slots.o dbi_uprobes.o arch/asm/dbi_kprobes.o arch/dbi_kprobes.o dbi_kprobes.o
swap_kprobe-$(CONFIG_ARM) += arch/asm/dbi_kprobes_arm.o arch/asm/dbi_kprobes_thumb.o
