#ifndef _SYSCALL_LIST_H
#define _SYSCALL_LIST_H

#define SYSCALL_LIST \
	X(sys_accept4), \
	X(sys_accept), \
	X(sys_access), \
	X(sys_acct), \
	X(sys_bind), \
	X(sys_chdir), \
	X(sys_chmod), \
	X(sys_chown16), \
	X(sys_chown), \
	X(sys_chroot), \
	X(sys_clone), \
	X(sys_connect), \
	X(sys_creat), \
	X(sys_dup3), \
	X(sys_epoll_create1), \
	X(sys_epoll_ctl), \
	X(sys_epoll_pwait), \
	X(sys_epoll_wait), \
	X(sys_eventfd2), \
	X(sys_eventfd), \
	X(sys_execve), \
	X(sys_exit_group), \
	X(sys_exit), \
	X(sys_faccessat), \
	X(sys_fadvise64_64), \
	X(sys_fallocate), \
	X(sys_fanotify_init), \
	X(sys_fanotify_mark), \
	X(sys_fchmodat), \
	X(sys_fchownat), \
	X(sys_fgetxattr), \
	X(sys_flistxattr), \
	X(sys_fork), \
	X(sys_fremovexattr), \
	X(sys_fstat64), \
	X(sys_ftruncate64), \
	X(sys_futimesat), \
	X(sys_getcwd), \
	X(sys_getpeername), \
	X(sys_getsockname), \
	X(sys_getsockopt), \
	X(sys_getxattr), \
	X(sys_inotify_add_watch), \
	X(sys_inotify_init1), \
	X(sys_inotify_init), \
	X(sys_inotify_rm_watch), \
	X(sys_ipc), \
	X(sys_kill), \
	X(sys_linkat), \
	X(sys_link), \
	X(sys_listen), \
	X(sys_listxattr), \
	X(sys_lstat64), \
/* TODO: X(sys_lstat), */ \
	X(sys_mkdirat), \
	X(sys_mkdir), \
	X(sys_mknodat), \
	X(sys_mknod), \
	X(sys_mmap_pgoff), \
	X(sys_mount), \
	X(sys_msgctl), \
	X(sys_msgget), \
	X(sys_msgrcv), \
	X(sys_msgsnd), \
	X(sys_name_to_handle_at), \
/* TODO: X(sys_newfstatat), */ \
	X(sys_old_mmap), \
	X(sys_openat), \
	X(sys_open_by_handle_at), \
	X(sys_open), \
	X(sys_pause), \
	X(sys_pipe2), \
	X(sys_ppoll), \
	X(sys_pread64), \
	X(sys_preadv), \
	X(sys_pselect6), \
	X(sys_pwrite64), \
	X(sys_pwritev), \
	X(sys_readlinkat), \
	X(sys_readlink), \
	X(sys_recvfrom), \
	X(sys_recvmmsg), \
	X(sys_recvmsg), \
	X(sys_recv), \
	X(sys_removexattr), \
	X(sys_renameat), \
	X(sys_rename), \
	X(sys_rmdir), \
	X(sys_rt_sigaction), \
	X(sys_rt_sigprocmask), \
	X(sys_rt_sigsuspend), \
	X(sys_rt_sigtimedwait), \
	X(sys_rt_tgsigqueueinfo), \
	X(sys_semctl), \
	X(sys_semget), \
	X(sys_semop), \
	X(sys_semtimedop), \
	X(sys_sendfile64), \
	X(sys_sendfile), \
	X(sys_sendmmsg), \
	X(sys_sendmsg), \
	X(sys_send), \
	X(sys_sendto), \
	X(sys_setns), \
	X(sys_setsockopt), \
	X(sys_setxattr), \
	X(sys_shmat), \
	X(sys_shmctl), \
	X(sys_shmdt), \
	X(sys_shmget), \
	X(sys_shutdown), \
	X(sys_sigaction), \
/* TODO: X(sys_sigaltstack), */ \
	X(sys_signalfd4), \
	X(sys_signalfd), \
/* TODO: X(sys_signal), */ \
	X(sys_sigpending), \
	X(sys_sigprocmask), \
	X(sys_sigsuspend), \
	X(sys_socketcall), \
	X(sys_socketpair), \
	X(sys_socket), \
	X(sys_splice), \
	X(sys_stat64), \
	X(sys_statfs64), \
	X(sys_statfs), \
/* TODO: X(sys_stat), */ \
	X(sys_swapoff), \
	X(sys_swapon), \
	X(sys_symlinkat), \
	X(sys_symlink), \
	X(sys_syncfs), \
	X(sys_tee), \
	X(sys_tgkill), \
	X(sys_timerfd_create), \
	X(sys_timerfd_gettime), \
	X(sys_timerfd_settime), \
	X(sys_truncate64), \
	X(sys_truncate), \
	X(sys_umount), \
	X(sys_unlinkat), \
	X(sys_unlink), \
	X(sys_unshare), \
	X(sys_uselib), \
	X(sys_utimensat), \
	X(sys_utimes), \
	X(sys_utime), \
	X(sys_vfork), \
	X(sys_vmsplice), \
	X(sys_wait4), \
	X(sys_waitid)
/* TODO: X(sys_waitpid) */

#endif /* _SYSCALL_LIST_H */
