EXTRA_CFLAGS := $(extra_cflags)
KBUILD_EXTRA_SYMBOLS = $(src)/../writer/Module.symvers

obj-m := swap_sampler.o
swap_sampler-y := swap_sampler_module.o

ifdef CONFIG_HIGH_RES_TIMERS
    swap_sampler-y += sampler_hrtimer.o
else
    swap_sampler-y += sampler_timer.o
endif
