EXTRA_CFLAGS := $(extra_cflags)

obj-m := swap_message_parser.o
swap_message_parser-y := swap_msg_parser.o \
                         msg_parser.o \
                         msg_buf.o \
                         msg_cmd.o \
                         features.o
