EXTRA_CFLAGS := $(extra_cflags)

obj-m := swap_preload.o
swap_preload-y := preload_module.o \
                  preload_control.o \
                  preload_debugfs.o \
                  preload_probe.o \
                  preload_threads.o
